const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const current=JSON.parse(fs.readFileSync(path.join(root,'dashboard/current.json')));
const history=JSON.parse(fs.readFileSync(path.join(root,'dashboard/history/2026-09-22.json')));
const context=vm.createContext({document:{addEventListener(){}},console,current,history});
const script=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/boot\(\);\s*$/, '');
vm.runInContext(script,context);
vm.runInContext('HISTORY_PAYLOAD=history; SECURITY_INDEX=buildSecurityIndex(current,history);',context);
const value=code=>vm.runInContext(code,context);
assert.equal(value('highestAuthority(SECURITY_INDEX.get("SZSE:001389"))'),'CONTINUITY');
assert.equal(value('highestAuthority(SECURITY_INDEX.get("SZSE:301150"))'),'CONTINUITY');
assert.equal(value('highestAuthority(SECURITY_INDEX.get("SZSE:300502"))'),'FORMAL');
assert.equal(value('highestAuthority(SECURITY_INDEX.get("SZSE:301018"))'),'CONTINUITY');
assert.equal(current.modules.formal_weekly.data.formal_cards.length,3);
assert.match(value('contextTimelineHtml(SECURITY_INDEX.get("SZSE:001389"))'),/2026-W37/);
assert.match(value('contextTimelineHtml(SECURITY_INDEX.get("SZSE:001389"))'),/DOWNGRADE/);
assert.match(value('contextTimelineHtml(SECURITY_INDEX.get("SZSE:301150"))'),/等待行情/);
assert.match(value('watchlist(current)'),/2026-10-13/);
assert.match(value('weekly(current)'),/已兑现对象完整排名/);
assert.match(value('weekly(current)'),/重要近卡与风险落选/);
assert.match(value('weekly(current)'),/前周活动卡面未随输入保留/);
assert.match(value('opportunities(current)'),/历史提名/);
assert.match(value('progress(current)'),/历史来源/);
assert.match(value('renderResearchMarkdown("<script>alert(1)</script>")'),/&lt;script&gt;/);
assert.equal(history.source_cutoff,'2026-09-22T15:40:00+08:00');
assert.equal(history.modules.candidate_weekly.data.adoption_pending,true);
assert.equal(value('nextChecks(SECURITY_INDEX.get("SZSE:301018")).join(" ")').includes('验证公司与订单'),false);
console.log('continuity, authority, research coverage and escaping checks passed');
